project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>',
         views.category, name='category'),
    path('recipes/<int:id>', views.recipe, name='recipe'),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self) -> str:
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_unit = models.CharField(max_length=65)
    servigs = models.IntegerField()
    servigs_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_step_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', default=' ', blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self) -> str:
        return self.title

recipes/views.py
import os

# from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render

from utils.pagination import make_pagination_range

from .models import Recipe

# from utils.recipes.factory import make_recipe

PER_PAGE = int(os.environ.get('PER_PAGE', 4))


def home(request):

    recipes = Recipe.objects.filter(
        is_published=True
    ).order_by('-id')

    try:
        current_page = int(request.GET.get('page', 1))
    except ValueError:
        current_page = 1

    paginator = Paginator(recipes, PER_PAGE)
    page_obj = paginator.get_page(current_page)

    pagination_range = make_pagination_range(
        paginator.page_range,
        4,
        current_page
    )

    context = {
        # 'recipes': recipes,
        'recipes': page_obj,
        'pages': pagination_range,
    }
    return render(request, 'recipes/pages/home.html', context)


def category(request, category_id):

    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True
        ).order_by('-id')
    )

    context = {'recipes': recipes,
               'title': f'{recipes[0].category.name}'
               }
    return render(request, 'recipes/pages/category.html', context)


def recipe(request, id):

    recipe = get_object_or_404(Recipe, pk=id, is_published=True)

    context = {'recipe': recipe,
               'is_detail_page': True,
               }

    return render(request, 'recipes/pages/recipe-view.html', context)


def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        # like as (sql), can use 'i' in contains to ignore de case sensitive
        Q(
            Q(title__icontains=search_term) | Q(
                description__icontains=search_term),
        ),
        is_published=True
    ).order_by('-id')

    # Substituido pelo Q de fora sendo um AND,
    # apos a busca interna q conten o OR ( | )
    # recipes = recipes.filter(is_published=True)
    # recipes = recipes.order_by('-id')

    context = {
        'page_title': f'Search for "{search_term}"',
        'search_term': search_term,
        'recipes': recipes,
    }

    return render(request, 'recipes/pages/search.html', context)

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

    <div class="main-content main-content-list container">

        {% for recipe in recipes %}
            {% include 'recipes/partials/_recipe.html' %}
        {% endfor %}

    </div>

{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

{% include 'recipes/partials/_messages.html' %}

    <div class="main-content main-content-list container">

        {% for recipe in recipes %}
            {% include 'recipes/partials/_recipe.html' %}
        {% empty %}
        <div class="center">
            <h2>Not to see here ma brotha</h2>
        <div>
        {% endfor %}

    </div>

{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}{{ recipe.title }}{% endblock title %}

{% block content %}

    <div class="main-content main-content-detail container">

        {% include 'recipes/partials/_recipe.html' %}

    </div>

{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}

{% block title %}{{ page_title }}{% endblock title %}

{% block content %}

<div class="center">
    <h3>Result for "{{ search_term }}"</h3>
</div>

    <div class="main-content main-content-list container">

        {% for recipe in recipes %}
            {% include 'recipes/partials/_recipe.html' %}
        {% empty %}
        <div class="center">
            <h2>Not to see here ma brotha</h2>
        <div>
        {% endfor %}

    </div>

{% endblock content %}

recipes/templates/recipes/partials/_footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Archjoe</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/_head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css" integrity="sha512-8Vtie9oRR62i7vkmVUISvuwOeipGv8Jd+Sur/ORKDD5JiLgTGeBSkI3ISOhc730VGvA5VVQPwKIKlmi+zMZ71w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/brands.min.css" integrity="sha512-bSncow0ApIhONbz+pNI52n0trz5fMWbgteHsonaPk42JbunIeM9ee+zTYAUP1eLPky5wP0XZ7MSLAPxKkwnlzw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/solid.min.css" integrity="sha512-6/gTF62BJ06BajySRzTm7i8N2ZZ6StspU9uVWDdoBiuuNu5rs1a8VwiJ7skCz2BcvhpipLKfFerXkuzs+npeKA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/_header.html
<header class="main-header-container">
    <div class="main-header container">
        <h2>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h2>
    </div>
</header>

recipes/templates/recipes/partials/_messages.html
{% if messages %}
    <div class="main-content center container messages-container">
        {% for message in messages %}
        <div class="message {{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

recipes/templates/recipes/partials/_pagination.html
{% if recipes.has_other_pages %}
    <div class="conteiner paginator">
        {% for page in paginator_range.pagination  %}
            {{ page }}
        {% endfor %}
    </div>
{% endif %}

recipes/templates/recipes/partials/_recipe.html
<div class="recipe recipe-list-item">

    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <img src="{{ recipe.cover.url }}" alt="">
        </a>
    </div>

    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <h3 class="recipe-title">{{ recipe.title }}</h3>
        </a>
    </div>

    <div class="recipe-author">
        {% if recipe.author is not None %}
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
        </span>
    {% endif %}

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name  }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">

        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }}  {{ recipe.preparation_time_unit }}
            </div>
        </div>

        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if not is_datail_page %}

        <footer class="recipe-footer">
            
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
        
    {% endif %}

    {% if is_detail_page is True %}

        <div class="preparation-steps">

            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}

            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}

        </div>

    {% endif %}

</div>

recipes/templates/recipes/partials/_search.html
<div class="search-container">
        
    <div class="container">
        <form method="GET" action="{% url 'recipes:search' %}" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}"  required>
            <button type="submit" class="search-button"><i class="fa fa-search"></i></button>
        </form>
    </div>

</div>